name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch
  pull_request:
    types: [opened, synchronize, reopened] # Triggers the workflow on pull requests

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Ensures Java 21 is used

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and analyze with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean build sonarqube \
            -Dsonar.projectKey=shubham1957_BookStore \ # EDIT THIS: Replace 'your_project_key' with your actual SonarCloud project key
            -Dsonar.organization=testcrafters \ # EDIT THIS: Replace 'your_organization_key' with your actual SonarCloud organization key
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN # Uses the SONAR_TOKEN secret
